LBS_TO_KGS_FACTOR = 0.453592
INCHES_TO_CMS_FACTOR = 2.54
G_TO_LBS_FACTOR = 0.00220462262

tagnames = {
    # calculated properties
    'NET_CARBS': None,
    'OMEGA3': None,
    'OMEGA6': None,
    #######################

    'PROTEIN': 'PROCNT',
    'PROCNT': 'PROCNT',

    'LIPID': 'FAT',
    U'FAT': 'FAT',

    'CARBOHYDRATE': 'CHOCDF',
    U'CHOCDF': 'CHOCDF',

    U'ASH': 'ASH',

    'CALORIES': 'ENERC_KCAL',
    U'ENERC_KCAL': 'ENERC_KCAL',

    U'SUGAR': 'SUGAR',
    'GALACTOSE': 'GALS',
    U'GALS': 'GALS',
    'FIBER': 'FIBTG',
    U'FIBTG': 'FIBTG',
    U'STARCH': 'STARCH',
    'SUCROSE': 'SUCS',
    U'SUCS': 'SUCS',
    'GLUCOSE': 'GLUS',
    U'GLUS': 'GLUS',
    'FRUCTOSE': 'FRUS',
    U'FRUS': 'FRUS',
    'LACTOSE': 'LACS',
    U'LACS': 'LACS',
    'MALTOSE': 'MALS',
    U'MALS': 'MALS',
    'ALCOHOL': 'ALC',
    U'ALC': 'ALC',
    U'WATER': 'WATER',

    #U'': '',  # ADJUSTED PROTEIN ...
    U'CAFFN': 'CAFFN',
    U'THEBRN': 'THEBRN',
    U'ENERC_KJ': 'ENERC_KJ',

    # MINERALS
    'CALCIUM': 'CA',
    U'CA': 'CA',
    'IRON': 'FE',
    U'FE': 'FE',
    'MAGNESIUM': 'MG',
    U'MG': 'MG',
    'PHOSPHORUS': 'P',
    U'P': 'P',
    'POTASSIUM': 'K',
    U'K': 'K',
    'SODIUM': 'NA',
    U'NA': 'NA',
    'ZINC': 'ZN',
    U'ZN': 'ZN',
    'COPPER': 'CU',
    U'CU': 'CU',
    'FLOURIDE': 'FLD',
    U'FLD': 'FLD',
    'MANGANESE': 'MN',
    U'MN': 'MN',
    'SELENIUM': 'SE',
    U'SE': 'SE',

    # VITAMINS
    # A
    'VIT_A': 'VITA_IU',
    U'VITA_IU': 'VITA_IU',
    U'RETOL': 'RETOL',
    U'VITA_RAE': 'VITA_RAE',
    U'CRYPX': 'CRYPX',
    U'LYCPN': 'LYCPN',
    U'LUT+ZEA': 'LUT+ZEA',
    U'CARTB': 'CARTB',
    U'CARTA': 'CARTA',
    # E
    'VIT_E': 'TOCPHA',
    U'TOCPHA': 'TOCPHA',
    U'TOCPHB': 'TOCPHB',
    U'TOCPHG': 'TOCPHG',
    U'TOCPHD': 'TOCPHD',
    # D
    'VIT_D': 'VITD',
    U'VITD': 'VITD',
    U'ERGCAL': 'ERGCAL',
    U'CHOCAL': 'CHOCAL',
    # C
    'VIT_C': 'VITC',
    U'VITC': 'VITC',
    # BS
    'THIAMIN': 'THIA',
    U'THIA': 'THIA',
    'RIBOFLAVIN': 'RIBF',
    U'RIBF': 'RIBF',
    'NIACIN': 'NIA',
    U'NIA': 'NIA',
    'PANTOTHENIC_ACID': 'PANTAC',
    U'PANTAC': 'PANTAC',
    'VIT_B6': 'VITB6A',
    U'VITB6A': 'VITB6A',
    'FOLATE': 'FOL',
    U'FOL': 'FOL',
    'VIT_B12': 'VITB12',
    U'VITB12': 'VITB12',
    'CHOLINE': 'CHOLN',
    U'CHOLN': 'CHOLN',
    'VIT_K': 'VITK',
    U'VITK': 'VITK',
    U'FOLAC': 'FOLAC',
    U'FOLFD': 'FOLFD',
    U'FOLDFE': 'FOLDFE',
    'BETAINE': 'BETN',
    U'BETN': 'BETN',
    # AMINOS
    U'TRP_G': 'TRP_G',
    U'THR_G': 'THR_G',
    U'ILE_G': 'ILE_G',
    U'LEU_G': 'LEU_G',
    U'LYS_G': 'LYS_G',
    U'MET_G': 'MET_G',
    U'CYS_G': 'CYS_G',
    U'PHE_G': 'PHE_G',
    U'TYR_G': 'TYR_G',
    U'VAL_G': 'VAL_G',
    U'ARG_G': 'ARG_G',
    U'HISTN_G': 'HISTN_G',
    U'ALA_G': 'ALA_G',
    U'ASP_G': 'ASP_G',
    U'GLU_G': 'GLU_G',
    U'GLY_G': 'GLY_G',
    U'PRO_G': 'PRO_G',
    U'SER_G': 'SER_G',
    U'HYP': 'HYP',
    #U'': '',
    #U'': '',
    # FAT
    'CHOLESTEROL': 'CHOLE',
    U'CHOLE': 'CHOLE',
    U'PHYSTR': 'PHYSTR',
    U'STID7': 'STID7',
    U'CAMD5': 'CAMD5',
    U'SITSTR': 'SITSTR',

    'TRANS_FAT': 'FATRN',
    U'FATRN': 'FATRN',
    U'FATRNM': 'FATRNM',
    U'FATRNP': 'FATRNP',

    'SATURATED_FAT': 'FASAT',
    U'FASAT': 'FASAT',
    U'F4D0': 'F4D0',
    U'F6D0': 'F6D0',
    U'F8D0': 'F8D0',
    U'F10D0': 'F10D0',
    U'F12D0': 'F12D0',
    U'F14D0': 'F14D0',
    U'F16D0': 'F16D0',
    U'F18D0': 'F18D0',
    U'F20D0': 'F20D0',
    U'F22D0': 'F22D0',
    U'F13D0': 'F13D0',
    U'F15D0': 'F15D0',
    U'F17D0': 'F17D0',
    U'F24D0': 'F24D0',

    'MONOUNSATURATED_FAT': 'FAMS',
    U'FAMS': 'FAMS',
    U'F18D1': 'F18D1',
    U'F14D1': 'F14D1',
    U'F16D1': 'F16D1',
    U'F20D1': 'F20D1',
    U'F22D1': 'F22D1',
    U'F16D1T': 'F16D1T',
    U'F18D1T': 'F18D1T',
    U'F24D1C': 'F24D1C',
    U'F16D1C': 'F16D1C',
    U'F18D1C': 'F18D1C',
    U'F15D1': 'F15D1',
    U'F17D1': 'F17D1',
    #(U'', U'22:1 T'),
    #(U'', U'22:1 C'),

    'POLYUNSATURATED_FAT': 'FAPU',
    U'FAPU': 'FAPU',
    U'F18D2': 'F18D2',
    U'F18D3': 'F18D3',
    U'F20D4': 'F20D4',
    U'F22D6': 'F22D6',
    U'F18D4': 'F18D4',
    U'F20D5': 'F20D5',
    U'F22D5': 'F22D5',
    U'F18D2TT': 'F18D2TT',
    U'F18D2CLA': 'F18D2CLA',
    U'F20D2CN6': 'F20D2CN6',
    U'F18D2CN6': 'F18D2CN6',
    U'F18D3CN6': 'F18D3CN6',
    U'F20D3': 'F20D3',
    U'F18D3CN3': 'F18D3CN3',
    U'F20D3N3': 'F20D3N3',
    U'F20D3N6': 'F20D3N6',
    U'F20D4N6': 'F20D4N6',
    U'F21D5': 'F21D5',
    U'F22D4': 'F22D4',
    #(u'', u'18:2 t not further defined'),
    #(u'', u'18:2 i'),
    #(u'', u'18:3i'),
}
